### ISSUE TITLE
Errors in FF and Safari

### ISSUE THREAD

**Issue by marthinal** [pions/demo-conference#8]
The errors are related to https://github.com/pion/pion-browser-client. There is already a PR that fixes the problem. See https://github.com/pion/pion-browser-client/pull/2

I can confirm that it works as expected.

Thanks for this example. It helps me understand WebRTC.

**Comment by Sean-Der** [comment]
Sorry I didn't respond sooner @marthinal glad the code help!

As Pion has grown we have concentrated more on other projects. I am deprecating this repo now to focus more on others.
